# Teste de Machine Learning

## Preparando os dados

In [4]:
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_csv('/content/drive/MyDrive/Estatística para Ciência de Dados e Machine Learning/Bases de dados/credit_data.csv')

In [6]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [7]:
dataset

,i#clientid,income,age,loan,c#default
0,1,66155.925095,59.017015,8106.532131,0
1,2,34415.153966,48.117153,6564.745018,0
2,3,57317.170063,63.108049,8020.953296,0
3,4,42709.534201,45.751972,6103.642260,0
4,5,66952.688845,18.584336,8770.099235,1
...,...,...,...,...,...
1995,1996,59221.044874,48.518179,1926.729397,0
1996,1997,69516.127573,23.162104,3503.176156,0
1997,1998,44311.449262,28.017167,5522.786693,1
1998,1999,43756.056605,63.971796,1622.722598,0


In [8]:
X = dataset.iloc[:,1:4].values
Y = dataset.iloc[:,4].values

In [9]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [10]:
Y

array([0, 0, 0, ..., 1, 0, 0])

## Importando Bibliotecas para o teste

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

## Treinamento


In [12]:
from numpy.random import logistic
results_naive_bayes = []
results_logistics = []
results_forest = []

for i in range(30):
  x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=i)

  naive_bayes = GaussianNB()
  naive_bayes.fit(x_train, y_train)
  forecast_nb = naive_bayes.predict(x_test)
  results_naive_bayes.append(accuracy_score(y_test, forecast_nb))

  logistics_regression = LogisticRegression()
  logistics_regression.fit(x_train, y_train)
  forecast_lr = logistics_regression.predict(x_test)
  results_logistics.append(accuracy_score(y_test, forecast_lr))

  forest = RandomForestClassifier()
  forest.fit(x_train, y_train)
  forecast_f = forest.predict((x_test))
  results_forest.append(accuracy_score(y_test, forecast_f))

## Resultados

In [13]:
print(results_naive_bayes)


[0.925, 0.925, 0.9325, 0.925, 0.92, 0.905, 0.9175, 0.9175, 0.9125, 0.9325, 0.9225, 0.9125, 0.935, 0.9175, 0.925, 0.9175, 0.9275, 0.92, 0.9325, 0.92, 0.93, 0.905, 0.9175, 0.9325, 0.9425, 0.9375, 0.94, 0.92, 0.935, 0.925]


In [14]:
print(results_logistics)


[0.9325, 0.9275, 0.9375, 0.94, 0.94, 0.95, 0.955, 0.9425, 0.935, 0.955, 0.945, 0.9325, 0.95, 0.935, 0.9425, 0.9425, 0.9525, 0.9475, 0.96, 0.9425, 0.9575, 0.9375, 0.9525, 0.97, 0.94, 0.9475, 0.955, 0.9625, 0.9575, 0.945]


In [15]:
print(results_forest)

[0.9775, 0.9875, 0.9825, 0.9925, 0.98, 0.985, 0.985, 0.985, 0.9775, 0.99, 0.9825, 0.98, 0.98, 0.985, 0.9825, 0.9775, 0.985, 0.9825, 0.99, 0.985, 0.9825, 0.9725, 0.9825, 0.985, 0.9825, 0.9925, 0.9875, 0.9825, 0.99, 0.99]


## Transformando os dados para uma nparray


In [16]:
results_naive_bayes = np.array(results_naive_bayes)
results_logistics = np.array(results_logistics)
results_forest = np.array(results_forest)

## Média

In [17]:
print(f"Naive Bayes: {results_naive_bayes.mean()}")
print(f"Logistic Regression: {results_logistics.mean()}")
print(f"Random Forest: {results_forest.mean()}")

Naive Bayes: 0.92425
Logistic Regression: 0.9463333333333334
Random Forest: 0.984


## Moda

In [18]:
from scipy import stats

In [19]:
stats.mode(results_naive_bayes), stats.mode(results_logistics), stats.mode(results_forest)
print(f"Naive Bayes: {stats.mode(results_naive_bayes)[0]} - Count: {stats.mode(results_naive_bayes)[1]}")
print(f"Logistic Regression: {stats.mode(results_logistics)[0]} - Count: {stats.mode(results_logistics)[1]}")
print(f"Random Forest: {stats.mode(results_forest)[0]} - Count: {stats.mode(results_forest)[1]}")

Naive Bayes: 0.9175 - Count: 5
Logistic Regression: 0.9425 - Count: 4
Random Forest: 0.9825 - Count: 8


In [20]:
import statistics

In [21]:
print(f"Naive Bayes: {statistics.mode(results_naive_bayes)}")
print(f"Logistic Regression: {statistics.mode(results_logistics)}")
print(f"Random Forest: {statistics.mode(results_forest)}")

Naive Bayes: 0.925
Logistic Regression: 0.9425
Random Forest: 0.9825


## Mediana

In [22]:
print(f"Naive Bayes: {np.median(results_naive_bayes)}")
print(f"Logistic Regression: {np.median(results_logistics)}")
print(f"Random Forest: {np.median(results_forest)}")


Naive Bayes: 0.925
Logistic Regression: 0.945
Random Forest: 0.98375


## Variação

In [23]:
np.set_printoptions(suppress=True)

print(f"Naive Bayes: {np.var(results_naive_bayes)}")
print(f"Logistic Regression: {np.var(results_logistics)}")
print(f"Random Forest: {np.var(results_forest)}")

Naive Bayes: 8.756250000000001e-05
Logistic Regression: 9.738888888888882e-05
Random Forest: 2.149999999999997e-05


In [24]:
np.min([8.756250000000001e-0, 9.738888888888882e-05, 3.5305555555555595e-05])

np.float64(3.5305555555555595e-05)

In [25]:
np.max([8.756250000000001e-0, 9.738888888888882e-05, 3.5305555555555595e-05])

np.float64(8.756250000000001)

In [26]:
results_naive_bayes

array([0.925 , 0.925 , 0.9325, 0.925 , 0.92  , 0.905 , 0.9175, 0.9175,
       0.9125, 0.9325, 0.9225, 0.9125, 0.935 , 0.9175, 0.925 , 0.9175,
       0.9275, 0.92  , 0.9325, 0.92  , 0.93  , 0.905 , 0.9175, 0.9325,
       0.9425, 0.9375, 0.94  , 0.92  , 0.935 , 0.925 ])

## Desvio Padrão

In [27]:
print(f"Naive Bayes: {np.std(results_naive_bayes)}" )
print(f"Logistic Regression: {np.std(results_logistics)}")
print(f"Random Forest: {np.std(results_forest)}")

Naive Bayes: 0.00935748363610645
Logistic Regression: 0.009868580895391638
Random Forest: 0.004636809247747849


## Coeficiente de Variação

In [28]:
print(f"Naive Bayes: {stats.variation(results_naive_bayes) * 100}")
print(f"Logistic Regression: {stats.variation(results_logistics) * 100}")
print(f"Random Forest: {stats.variation(results_forest) * 100}")


Naive Bayes: 1.0124407504578252
Logistic Regression: 1.042822919555298
Random Forest: 0.47122045200689516


## Validação Cruzada

In [31]:
from sklearn.model_selection import cross_val_score, KFold

In [32]:
results_naive_bayes_cv = []
results_logistics_cv = []
results_forest_cv = []

for i in range(30):
  kfold = KFold(n_splits=10, shuffle=True, random_state=i)

  naive_bayes = GaussianNB()
  scores_nb = cross_val_score(naive_bayes, X, Y, cv=kfold)
  results_naive_bayes_cv.append(scores_nb.mean())

  logistics_regression = LogisticRegression()
  scores_lr = cross_val_score(logistics_regression, X, Y, cv=kfold)
  results_logistics_cv.append(scores_lr.mean())

  forest = RandomForestClassifier()
  scores_f = cross_val_score(forest, X, Y, cv=kfold)
  results_forest_cv.append(scores_f.mean())

### Resultado

In [38]:
print(f"Naive Bayes Results: {np.array(results_naive_bayes_cv)}\n")
print(f"Logistic Regression Results: {np.array(results_logistics_cv)}\n")
print(f"Random Forest: {np.array(results_forest_cv)}")

Naive Bayes Results: [0.92486181 0.92491709 0.92488945 0.92288191 0.92487186 0.92538945
 0.92438442 0.92488945 0.92487186 0.92388945 0.92538442 0.92440201
 0.92537437 0.92439447 0.92538693 0.92488191 0.92588442 0.92489447
 0.92388191 0.92588442 0.92589447 0.92538945 0.92436432 0.92638442
 0.92289447 0.92538945 0.92488693 0.92539196 0.92538191 0.92588442]

Logistic Regression Results: [0.94342714 0.94590201 0.94391206 0.94340704 0.94591457 0.9429196
 0.94390955 0.94590201 0.94491709 0.94442462 0.94442211 0.94592714
 0.94341709 0.94440704 0.94490452 0.94442462 0.94493719 0.94591206
 0.9453995  0.9444196  0.94592965 0.94490955 0.9454196  0.94390452
 0.94540452 0.94592714 0.94593719 0.9444196  0.94692714 0.94391709]

Random Forest: [0.98647236 0.98548492 0.98447487 0.98697487 0.98798492 0.98448241
 0.9884799  0.98798995 0.98497487 0.9854799  0.98898241 0.98697236
 0.98596985 0.98898241 0.98698744 0.98898744 0.98648492 0.98647236
 0.98648492 0.9844799  0.98647487 0.98698241 0.98497739 0.987

### Media

In [34]:
print(f"Naive Bayes: {np.array(results_naive_bayes_cv).mean()}")
print(f"Logistic Regression: {np.array(results_logistics_cv).mean()}")
print(f"Random Forest: {np.array(results_forest_cv).mean()}")


Naive Bayes: 0.9249359296482411
Logistic Regression: 0.9448500837520938
Random Forest: 0.9868308207705193


In [41]:
print(f"Naive Bayes Variation: {stats.variation(results_naive_bayes) * 100}")
print(f"Logistic Regression Variation: {stats.variation(results_logistics) * 100}")
print(f"Random Forest Variation: {stats.variation(results_forest) * 100}")

Naive Bayes Variation: 1.0124407504578252
Logistic Regression Variation: 1.042822919555298
Random Forest Variation: 0.47122045200689516


In [40]:
print(f"Naive Bayes Variation: {stats.variation(results_naive_bayes_cv) * 100}")
print(f"Logistic Regression Variation: {stats.variation(results_logistics_cv) * 100}")
print(f"Random Forest Variation: {stats.variation(results_forest_cv) * 100}")

Naive Bayes Variation: 0.08641071566366061
Logistic Regression Variation: 0.10394366203474359
Random Forest Variation: 0.14186263387347656
