# Teste de Machine Learning

## Preparando os dados

In [14]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/Estatística para Ciência de Dados e Machine Learning/Bases de dados/credit_data.csv')

In [3]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [4]:
dataset

,i#clientid,income,age,loan,c#default
0,1,66155.925095,59.017015,8106.532131,0
1,2,34415.153966,48.117153,6564.745018,0
2,3,57317.170063,63.108049,8020.953296,0
3,4,42709.534201,45.751972,6103.642260,0
4,5,66952.688845,18.584336,8770.099235,1
...,...,...,...,...,...
1995,1996,59221.044874,48.518179,1926.729397,0
1996,1997,69516.127573,23.162104,3503.176156,0
1997,1998,44311.449262,28.017167,5522.786693,1
1998,1999,43756.056605,63.971796,1622.722598,0


In [5]:
X = dataset.iloc[:,1:4].values
Y = dataset.iloc[:,4].values

In [6]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [7]:
Y

array([0, 0, 0, ..., 1, 0, 0])

## Importando Bibliotecas para o teste

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

## Treinamento


In [9]:
from numpy.random import logistic
results_naive_bayes = []
results_logistics = []
results_forest = []

for i in range(30):
  x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=i)

  naive_bayes = GaussianNB()
  naive_bayes.fit(x_train, y_train)
  forecast_nb = naive_bayes.predict(x_test)
  results_naive_bayes.append(accuracy_score(y_test, forecast_nb))

  logistics_regression = LogisticRegression()
  logistics_regression.fit(x_train, y_train)
  forecast_lr = logistics_regression.predict(x_test)
  results_logistics.append(accuracy_score(y_test, forecast_lr))

  forest = RandomForestClassifier()
  forest.fit(x_train, y_train)
  forecast_f = forest.predict((x_test))
  results_forest.append(accuracy_score(y_test, forecast_f))

## Resultados

In [11]:
print(results_naive_bayes)


[0.925, 0.925, 0.9325, 0.925, 0.92, 0.905, 0.9175, 0.9175, 0.9125, 0.9325, 0.9225, 0.9125, 0.935, 0.9175, 0.925, 0.9175, 0.9275, 0.92, 0.9325, 0.92, 0.93, 0.905, 0.9175, 0.9325, 0.9425, 0.9375, 0.94, 0.92, 0.935, 0.925]


In [12]:
print(results_logistics)


[0.9325, 0.9275, 0.9375, 0.94, 0.94, 0.95, 0.955, 0.9425, 0.935, 0.955, 0.945, 0.9325, 0.95, 0.935, 0.9425, 0.9425, 0.9525, 0.9475, 0.96, 0.9425, 0.9575, 0.9375, 0.9525, 0.97, 0.94, 0.9475, 0.955, 0.9625, 0.9575, 0.945]


In [13]:
print(results_forest)

[0.975, 0.99, 0.9825, 0.9925, 0.98, 0.985, 0.985, 0.985, 0.9725, 0.9875, 0.9825, 0.975, 0.975, 0.985, 0.98, 0.98, 0.9875, 0.9775, 0.99, 0.985, 0.9825, 0.975, 0.9825, 0.9875, 0.9825, 0.995, 0.995, 0.9825, 0.99, 0.99]


## Transformando os dados para uma nparray


In [15]:
results_naive_bayes = np.array(results_naive_bayes)
results_logistics = np.array(results_logistics)
results_forest = np.array(results_forest)

## Média

In [43]:
print(f"Naive Bayes: {results_naive_bayes.mean()}")
print(f"Logistic Regression: {results_logistics.mean()}")
print(f"Random Forest: {results_forest.mean()}")

Naive Bayes: 0.92425
Logistic Regression: 0.9463333333333334
Random Forest: 0.9838333333333333


## Moda

In [33]:
from scipy import stats

In [44]:
stats.mode(results_naive_bayes), stats.mode(results_logistics), stats.mode(results_forest)
print(f"Naive Bayes: {stats.mode(results_naive_bayes)[0]} - Count: {stats.mode(results_naive_bayes)[1]}")
print(f"Logistic Regression: {stats.mode(results_logistics)[0]} - Count: {stats.mode(results_logistics)[1]}")
print(f"Random Forest: {stats.mode(results_forest)[0]} - Count: {stats.mode(results_forest)[1]}")

Naive Bayes: 0.9175 - Count: 5
Logistic Regression: 0.9425 - Count: 4
Random Forest: 0.9825 - Count: 6


In [34]:
import statistics

In [42]:
print(f"Naive Bayes: {statistics.mode(results_naive_bayes)}")
print(f"Logistic Regression: {statistics.mode(results_logistics)}")
print(f"Random Forest: {statistics.mode(results_forest)}")

Naive Bayes: 0.925
Logistic Regression: 0.9425
Random Forest: 0.9825


## Mediana

In [45]:
print(f"Naive Bayes: {np.median(results_naive_bayes)}")
print(f"Logistic Regression: {np.median(results_logistics)}")
print(f"Random Forest: {np.median(results_forest)}")


Naive Bayes: 0.925
Logistic Regression: 0.945
Random Forest: 0.98375


## Variação

In [58]:
np.set_printoptions(suppress=True)

print(f"Naive Bayes: {np.var(results_naive_bayes)}")
print(f"Logistic Regression: {np.var(results_logistics)}")
print(f"Random Forest: {np.var(results_forest)}")

Naive Bayes: 8.756250000000001e-05
Logistic Regression: 9.738888888888882e-05
Random Forest: 3.5305555555555595e-05


In [56]:
np.min([8.756250000000001e-0, 9.738888888888882e-05, 3.5305555555555595e-05])

np.float64(3.5305555555555595e-05)

In [59]:
np.max([8.756250000000001e-0, 9.738888888888882e-05, 3.5305555555555595e-05])

np.float64(8.756250000000001)

In [55]:
results_naive_bayes

array([0.925 , 0.925 , 0.9325, 0.925 , 0.92  , 0.905 , 0.9175, 0.9175,
       0.9125, 0.9325, 0.9225, 0.9125, 0.935 , 0.9175, 0.925 , 0.9175,
       0.9275, 0.92  , 0.9325, 0.92  , 0.93  , 0.905 , 0.9175, 0.9325,
       0.9425, 0.9375, 0.94  , 0.92  , 0.935 , 0.925 ])

## Desvio Padrão

In [40]:
print(f"Naive Bayes: {np.std(results_naive_bayes)}" )
print(f"Logistic Regression: {np.std(results_logistics)}")
print(f"Random Forest: {np.std(results_forest)}")

Naive Bayes: 0.00935748363610645
Logistic Regression: 0.009868580895391638
Random Forest: 0.005941847823325299


## Coeficiente de Variação

In [62]:
print(f"Naive Bayes: {stats.variation(results_naive_bayes) * 100}")
print(f"Logistic Regression: {stats.variation(results_logistics) * 100}")
print(f"Random Forest: {stats.variation(results_forest) * 100}")


Naive Bayes: 1.0124407504578252
Logistic Regression: 1.042822919555298
Random Forest: 0.6039486183288462
